### ISSUE TITLE
Add chooseMap

### ISSUE THREAD

**Issue by treeowl** [sjoerdvisscher/unfoldable#7]
A number of `Unfolder` instances use `choose (map f ...)`. This suggests it could be helpful to add a method `chooseMap :: (a -> f b) -> [a] -> f b`, or possibly even `chooseMap :: Foldable t => (a -> f b) -> t a -> f b`.

**Comment by sjoerdvisscher** [comment]
I don't think adding `Foldable` would work. It makes implementing `choose(Map)` much more annoying without practical gain.

But having `chooseMap` is a great idea!

**Comment by sjoerdvisscher** [comment]
I added `chooseMap`, worked out great, thanks!
