### ISSUE TITLE
compile error with GHC 7.6

### ISSUE THREAD

**Issue by hvr** [sjoerdvisscher/unfoldable#8]
This is a curious one... the default install-plan for GHC 7.8 and GHC 7.4 works fine, but with GHC 7.6 we get this:

```
In order, the following will be built (use -v for more details):
 - unfoldable-0.9.1 {unfoldable-0.9.1-inplace} (lib:unfoldable) (first run)
Configuring unfoldable-0.9.1...
Preprocessing library unfoldable-0.9.1...
[1 of 3] Compiling Data.Unfolder    ( src/Data/Unfolder.hs, /tmp/matrix-worker/1480811729/dist-newstyle/build/x86_64-linux/ghc-7.6.3/unfoldable-0.9.1/build/Data/Unfolder.o )

src/Data/Unfolder.hs:228:10:
    No instance for (Alternative S.Seq)
      arising from the superclasses of an instance declaration
    Possible fix: add an instance declaration for (Alternative S.Seq)
    In the instance declaration for `Unfolder S.Seq'
```

**Comment by sjoerdvisscher** [comment]
There's an Alternative instance since containers 0.5.2.0. Can you see which version of containers is used?

**Comment by hvr** [comment]
indeed, that's it. GHC 7.4.2 forced the solver to pick a version higher than 0.5, and it reached for the latest one; GHC 7.6 however happened to have 0.5.0 as boot library, so cabal reused that one.

 I can confirm that 0.5.2 is the lowest version which works. I've tweaked the lower bounds accordingly:

- https://hackage.haskell.org/package/unfoldable-0.9.1/revisions/
- https://hackage.haskell.org/package/unfoldable-0.9/revisions/
